### ISSUE TITLE
Does this work offline?

### ISSUE THREAD

**Issue by RayBB** [sysdrum/notion-app#1]

**Comment by sysdrum** [comment]
Not at this time but I am working on it. Once I have a working solution I will update and post it.

**Comment by RayBB** [comment]
Thanks I would find that super useful :)

**Comment by Rep8** [comment]
@RayBB 
I've run the windows version via wine/playonlinux and it runs pretty well.
It supports offline storage and also internal updating.

I also mentioned this to one of their team members a while ago and they have their eye on a Linux release.

This project is also nice to have if you don't want to mess around with wine.

**Comment by sysdrum** [comment]
I have contacted notion.so about working on the offline mode. I do not work for notion.so this was built as stop gap until they either adopt solutions for linux users or create one.
The current answer I have from them is this:
"Hey we'll support an full offline version soon (and possibly an official Linux client!) I wouldn't recommend you to touch it as that could cause data loss. Thanks for understanding."
There are thing that require access I do not have to make offline work.

**Comment by RayBB** [comment]
Thanks for the update! I appreciate you reaching out

**Comment by uWinkel** [comment]
Any comments on how to use it with wine? I am getting errors that core Libarys are missing like

`err:module:import_dll Library UIAutomationCore.DLL 
err:module:LdrInitializeThunk Main exe initialization for L"C:\\users\user\\Local Settings\\Application Data\\Programs\\Notion\\Notion.exe" failed, status c0000135
`

**Comment by sysdrum** [comment]
@uWinkel There is no need to use it with wine? It runs native.

**Comment by sysdrum** [comment]
No, notion.so has the required offline features locked no matter which way you build the .js (DMG way being the wrong solution not sure why that is even a thing.) I have a work around but when they push changes it breaks and I have to rebuild. 
They are great but it does not look like they are going to build a native app that supports offline mode anytime soon. "There is just not enough interest from the Linux community"
