### ISSUE TITLE
Is there actual source code for the text editor?

### ISSUE THREAD

**Issue by motoco** [sysdrum/notion-app#4]
Thanks so much for this project.

Been trying to get notion up and running o Linux for a while and would like to make some small tweaks to the text editor part. Do you know if these files obfuscated by Notion?

**Comment by sysdrum** [comment]
All direct files for the function of the web app are on notion.so side. This is just a wrapper to make it work like a native app on gtk and qt systems.

**Comment by danielelisi** [comment]
The backend for the Notion platform is proprietary software. Hard to believe they will ever release it as an open source project
