### ISSUE TITLE
Create Desktop Shortcut script doesn't work

### ISSUE THREAD

**Issue by prabhumarappan** [sysdrum/notion-app#5]
On a freshly installed Xubuntu (18.04.2) environment, the create desktop shortcut script does not work.

This is happening because `applications` folder does not exist in `~/.local/share/`.
And because of the copy command 
`cp -p Notion.desktop ~/.local/share/applications`
The desktop shortcut `Notion.desktop` is being copied to the file `~/.local/share/applications` instead of being copied into the folder `~/.local/share/applications/`

Is this something which is meant to be?
If not, I think this can be fixed by first creating the `applications` folder and then doing a copy.

**Comment by sysdrum** [comment]
The folder should already be in place. As it is required for extending support for software outside of the core system.

**Comment by prabhumarappan** [comment]
Got your point, the issue created above was specific to Xubuntu.
Right now, i tried creating a new user in Ubuntu 18.04 (Office machine) and the folder `.local/share/applications/` was already there.

@sysdrum I'll try creating a new user in Xubuntu, and if the applications folder is created, I will close this issue.

**Comment by sysdrum** [comment]
I have updated the desktop shortcut script to account for systems that may not have the folder.
