### ISSUE TITLE
Icons are missing. Is this a system thing?

### ISSUE THREAD

**Issue by kybian** [sysdrum/notion-app#7]
My icons (the emojis on the pages) aren't showing up. Most of them are boxes; some are very primitive looking icons that are definitely not the same as what I see on my browser. I think this may be a system thing because I don't have emojis installed or something, but since this is related to this app, I decided to open an issue.

**Comment by sysdrum** [comment]
This is issue is not related to the wrapper but a sync issue with notion.so.

**Comment by LinuxIsCool** [comment]
I'm having the same issue.

**Comment by sysdrum** [comment]
This is issue is not related to the wrapper but a sync issue with notion.so.
